#!/usr/bin/env python3

from string import Template
import argparse

parser = argparse.ArgumentParser(prog="render_tpl")
parser.add_argument("file")
parser.add_argument("-v", "--var", action="append", help="variable")

args = parser.parse_args()


def parse_var(var_text):
    return var_text.split("=")


var_list = []
for var in args.var:
    var_list.append(parse_var(var))

f = open(args.file, "r")
template = Template(f.read())
f.close()

content = template.substitute(dict(var_list))

print(content)
